# Site Settings
title: "Mikhail Ulanov"
email: "mulanov@gmail.com"
description: "Academic website of Mikhail Ulanov"
baseurl: ""
url: "https://mulanov.github.io"
github_username: mulanov

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Navigation
nav_pages:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "News"
    url: "/news/"
  - title: "CV"
    url: "/cv/"
  - title: "Research"
    url: "/research/"
  - title: "Collaborations"
    url: "/collaborations/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Links"
    url: "/links/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"